name: Build Python wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --manylinux 2014
          working-directory: pybpe_openai
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: pybpe_openai/dist/
