name: Build Python wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: List files
        run: |
          echo "==== ROOT ===="
          pwd
          ls -l
          echo "==== PYBPE_OPENAI ===="
          ls -l pybpe_openai
          echo "==== RUST-GEMS ===="
          ls -l rust-gems
      - name: Build wheels (manylinux)
        uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: pybpe_openai
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: pybpe_openai/dist/
